// Generated by CoffeeScript 1.6.3
(function($, window, document) {
  var Console;
  $.prototype.console = function($options) {
    if ($options == null) {
      $options = {};
    }
    if (!$.data(this, 'console')) {
      return $.data(this, 'console', new Console(this, $options));
    }
  };
  return Console = (function() {
    function Console($this, $options) {
      console.log($options);
      console.log($this);
    }

    return Console;

  })();
})(jQuery, window, document);
