// Generated by CoffeeScript 1.6.3
(function($, window, document) {
  var _defaults;
  _defaults = {
    color: "#556b2f",
    backgroundColor: "white"
  };
  return $.prototype.greenify = function($options) {
    var _options;
    if ($options == null) {
      $options = {};
    }
    _options = $.extend(_defaults, $options);
    this.css({
      color: _options.color,
      backgroundColor: _options.backgroundColor
    });
    return this;
  };
})(jQuery, window, document);
