// Generated by CoffeeScript 1.6.3
(function($, window, document, undefined_) {
  return $.widget("namespace.widgetname", {
    options: {
      someValue: null
    },
    _create: function() {},
    destroy: function() {
      return $.Widget.prototype.destroy.call(this);
    },
    methodB: function(event) {
      return this._trigger("methodA", event, {
        key: value
      });
    },
    methodA: function(event) {
      return this._trigger("dataChanged", event, {
        key: value
      });
    },
    _setOption: function(key, value) {
      switch (key) {
        case "someValue":
          break;
      }
      return $.Widget.prototype._setOption.apply(this, arguments_);
    }
  });
})(jQuery, window, document);
